<a href="https://colab.research.google.com/github/Romane-lrnt/GitConcepts/blob/main/Cours5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
n=int(input('Enter the value of n: '))
for i in range(1, n+1, 2):
  q_i=i**2
  print(q_i)

Enter the value of n: 10
1
9
25
49
81

In [ ]:
sum=0
for i in range(6):
  sum=sum+i
  print(f"The value of sum is in each iteration: {sum}")
print("The sum is valid {}".format(sum))

The value of sum is in each iteration: 0
The value of sum is in each iteration: 1
The value of sum is in each iteration: 3
The value of sum is in each iteration: 6
The value of sum is in each iteration: 10
The value of sum is in each iteration: 15
The sum is valid 15

In [ ]:
prod=1
for i in range(1,6):
  prod=prod*i
  print("The partial sum is {}".format(prod))
print("Total sum: {}".format(sum))

The partial sum is 1
The partial sum is 2
The partial sum is 6
The partial sum is 24
The partial sum is 120
Total sum: 15

In [ ]:
for i in range(4):
  for j in range(3):
    print("i={}, j={}".format(i, j))

i=0, j=0
i=0, j=1
i=0, j=2
i=1, j=0
i=1, j=1
i=1, j=2
i=2, j=0
i=2, j=1
i=2, j=2
i=3, j=0
i=3, j=1
i=3, j=2
i=0, j=0
i=0, j=1
i=0, j=2
i=1, j=0
i=1, j=1
i=1, j=2
i=2, j=0
i=2, j=1
i=2, j=2
i=3, j=0
i=3, j=1
i=3, j=2

In [ ]:
n=int(input("Enter the value of n: "))
sum=0
for i in range(n+1):
  sum=sum+i
print("The value of the sum is: {}".format(sum))

Enter the value of n: 7
The value of the sum is: 28

In [ ]:
n=int(input("Enter the value of n: "))
sum=0
for j in range(1, n+1):
  q=(j+1)/(j**2)
  sum=sum+q
print("For n={} the result of the sum is approximately {: .2f}".format(n, sum)) #: .2f specifies 2 decimal places

Enter the value of n: 10
For n=10 the result of the sum is approximately  4.48

In [ ]:
n=int(input("Enter ta positive value: "))
fact=1
for j in range(1, n+1):
  fact=fact*j
print("{} factorial is {}".format(n, fact))

Enter ta positive value: 5
5 factorial is 120

In [ ]:
for i in range(1, 10):
  for j in range(1, 10):
    print("{}{}".format(i, j))

11
12
13
14
15
16
17
18
19
21
22
23
24
25
26
27
28
29
31
32
33
34
35
36
37
38
39
41
42
43
44
45
46
47
48
49
51
52
53
54
55
56
57
58
59
61
62
63
64
65
66
67
68
69
71
72
73
74
75
76
77
78
79
81
82
83
84
85
86
87
88
89
91
92
93
94
95
96
97
98
99

In [ ]:
for i in range(1, 10):
  for j in range(1, 10):
    if i!=j:
      print("{} {}".format(i, j))

1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
2 1
2 3
2 4
2 5
2 6
2 7
2 8
2 9
3 1
3 2
3 4
3 5
3 6
3 7
3 8
3 9
4 1
4 2
4 3
4 5
4 6
4 7
4 8
4 9
5 1
5 2
5 3
5 4
5 6
5 7
5 8
5 9
6 1
6 2
6 3
6 4
6 5
6 7
6 8
6 9
7 1
7 2
7 3
7 4
7 5
7 6
7 8
7 9
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 9
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8

In [ ]:
a=int(input("Enter the number of triangular numbers you want: "))
for i in range(0,a+1):
  t=i*(i+1)/2
  print(t)

Enter the number of triangular numbers you want: 6
0.0
1.0
3.0
6.0
10.0
15.0
21.0

In [ ]:
for i in range(1,10):
  for j in range(1,10):
    for k in range(1,10):
      print("{}{}{}".format(i,j,k))

111
112
113
114
115
116
117
118
119
121
122
123
124
125
126
127
128
129
131
132
133
134
135
136
137
138
139
141
142
143
144
145
146
147
148
149
151
152
153
154
155
156
157
158
159
161
162
163
164
165
166
167
168
169
171
172
173
174
175
176
177
178
179
181
182
183
184
185
186
187
188
189
191
192
193
194
195
196
197
198
199
211
212
213
214
215
216
217
218
219
221
222
223
224
225
226
227
228
229
231
232
233
234
235
236
237
238
239
241
242
243
244
245
246
247
248
249
251
252
253
254
255
256
257
258
259
261
262
263
264
265
266
267
268
269
271
272
273
274
275
276
277
278
279
281
282
283
284
285
286
287
288
289
291
292
293
294
295
296
297
298
299
311
312
313
314
315
316
317
318
319
321
322
323
324
325
326
327
328
329
331
332
333
334
335
336
337
338
339
341
342
343
344
345
346
347
348
349
351
352
353
354
355
356
357
358
359
361
362
363
364
365
366
367
368
369
371
372
373
374
375
376
377
378
379
381
382
383
384
385
386
387
388
389
391
392
393
394
395
396
397
398
399
411
412
413
414
415
416
417
418
419
421
422
423
424
425
426
427
428
429
431
432
433
434
435
436
437
438
439
441
442
443
444
445
446
447
448
449
451
452
453
454
455
456
457
458
459
461
462
463
464
465
466
467
468
469
471
472
473
474
475
476
477
478
479
481
482
483
484
485
486
487
488
489
491
492
493
494
495
496
497
498
499
511
512
513
514
515
516
517
518
519
521
522
523
524
525
526
527
528
529
531
532
533
534
535
536
537
538
539
541
542
543
544
545
546
547
548
549
551
552
553
554
555
556
557
558
559
561
562
563
564
565
566
567
568
569
571
572
573
574
575
576
577
578
579
581
582
583
584
585
586
587
588
589
591
592
593
594
595
596
597
598
599
611
612
613
614
615
616
617
618
619
621
622
623
624
625
626
627
628
629
631
632
633
634
635
636
637
638
639
641
642
643
644
645
646
647
648
649
651
652
653
654
655
656
657
658
659
661
662
663
664
665
666
667
668
669
671
672
673
674
675
676
677
678
679
681
682
683
684
685
686
687
688
689
691
692
693
694
695
696
697
698
699
711
712
713
714
715
716
717
718
719
721
722
723
724
725
726
727
728
729
731
732
733
734
735
736
737
738
739
741
742
743
744
745
746
747
748
749
751
752
753
754
755
756
757
758
759
761
762
763
764
765
766
767
768
769
771
772
773
774
775
776
777
778
779
781
782
783
784
785
786
787
788
789
791
792
793
794
795
796
797
798
799
811
812
813
814
815
816
817
818
819
821
822
823
824
825
826
827
828
829
831
832
833
834
835
836
837
838
839
841
842
843
844
845
846
847
848
849
851
852
853
854
855
856
857
858
859
861
862
863
864
865
866
867
868
869
871
872
873
874
875
876
877
878
879
881
882
883
884
885
886
887
888
889
891
892
893
894
895
896
897
898
899
911
912
913
914
915
916
917
918
919
921
922
923
924
925
926
927
928
929
931
932
933
934
935
936
937
938
939
941
942
943
944
945
946
947
948
949
951
952
953
954
955
956
957
958
959
961
962
963
964
965
966
967
968
969
971
972
973
974
975
976
977
978
979
981
982
983
984
985
986
987
988
989
991
992
993
994
995
996
997
998
999

In [ ]:
for i in range(1,10):
  for j in range(1,10):
    for k in range(1,10):
      if i+j+k==22:
        print("{}{}{}".format(i,j,k), end=" ")

499 589 598 679 688 697 769 778 787 796 859 868 877 886 895 949 958 967 976 985 994

In [ ]:
n=int(input("Enter an integer: "))
i=1
for i in range(1,n+1):
  if n%i==0:
    print(i,end=" ")
    i=i+1

Enter an integer: 395
1 5 79 395

In [ ]:
num=int(input("Enter a positive number: "))
sum=0
for i in range(num):
  odd_num=2*i+1
  print(f"The odd number is {odd_num}")
  sum=sum+odd_num
print(f"The sum of the first {num} odd numbers is {sum}.")

Enter a positive number: 5
The odd number is 1
The odd number is 3
The odd number is 5
The odd number is 7
The odd number is 9
The sum of the first 5 odd numbers is 25.

In [ ]:
n=int(input("Enter an integer: "))
result=False
for i in range(2, n):
  if n%i==0:
    result=True
if result==True:
  print(f"{n} is not a prime number")
else:
  print(f"{n} is a prime number")

Enter an integer: 51907
51907 is a prime number

In [ ]:
fi1=0
fi2=1
n=int(input("Enter the value of n: "))
for i in range(n+1):
  fii=fi1+fi2
  fi1=fi2
  fi2=fii
print(fii)

Enter the value of n: 5
13